title:               Enkrasia's Site
url:                 https://enkrasia.github.io
baseurl:             "https://enkrasia.github.io"

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle', '_posts\.obsidian', '_posts\Template', '_posts\.trash']

permalink:           none
paginate:            10
paginate_path:       /blog/:num

blog:
  truncated_preview: true

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              JW
  url:               
  email:             

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist